services:
  redis-service:
    container_name: redis_service
    restart: always
    image: redis:7.2.3-alpine
    environment:
      REDIS_ARGS: "--requirepass 1234 --user redis_db_user on >1234 ~* allcommands --user default off nopass nocommands"
    volumes:
      - redis-db:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  users-backend:
    build: backend/.
    container_name: users_backend
    command: sh -c "gunicorn main:app"
    volumes:
      - ./backend:/code
    depends_on:
      redis-service:
        condition: service_healthy
    env_file:
      - backend/.env
    networks:
      - internal
      - shared-network

volumes:
  redis-db:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
