services:
  app:
    build: .
    container_name: app
    command: sh -c "gunicorn $MAIN_APP.wsgi"
    volumes:
      - .:/code
    env_file:
      - .env

  proxy:
    image: nginx:1.25.4-alpine
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      app:
        condition: service_started
