# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/proto/deployment_plan.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1epb/proto/deployment_plan.proto\"&\n\x15\x44\x65ploymentPlanRequest\x12\r\n\x05token\x18\x01 \x01(\t\"T\n\x16\x44\x65ploymentPlanResponse\x12\x0c\n\x04plan\x18\x01 \x01(\t\x12\x15\n\rinstance_tier\x18\x02 \x01(\t\x12\x15\n\rinstance_type\x18\x03 \x01(\t2Y\n\x0e\x44\x65ploymentPlan\x12G\n\x12GetDeploymentPlans\x12\x16.DeploymentPlanRequest\x1a\x17.DeploymentPlanResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.proto.deployment_plan_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEPLOYMENTPLANREQUEST']._serialized_start=34
  _globals['_DEPLOYMENTPLANREQUEST']._serialized_end=72
  _globals['_DEPLOYMENTPLANRESPONSE']._serialized_start=74
  _globals['_DEPLOYMENTPLANRESPONSE']._serialized_end=158
  _globals['_DEPLOYMENTPLAN']._serialized_start=160
  _globals['_DEPLOYMENTPLAN']._serialized_end=249
# @@protoc_insertion_point(module_scope)
