services:
  admin-db:
    container_name: admin_db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  admin-backend:
    build: .
    container_name: admin_backend
    command: sh -c "alembic upgrade head && gunicorn main:app"
    volumes:
      - .:/code
    depends_on:
      admin-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal
      - shared-network

  admin-rmq:
    build: .
    container_name: admin_rmq
    command: sh -c "python3 message_queue.py"
    volumes:
      - .:/code
    depends_on:
      admin-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal
      - shared-network

volumes:
  postgres-db:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
