services:
  admin-db:
    container_name: admin_db
    restart: always
    image: postgres:16.1-alpine3.18
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  admin-backend:
    build: .
    container_name: admin_backend
    command: sh -c "gunicorn main:app"
    volumes:
      - .:/code
    healthcheck:
      test: ["CMD-SHELL", "curl", "--fail http://admin_backend/health-check/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      admin-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal
      - shared-network

  admin-frontend:
    build: frontend/Dockerfile
    container_name: admin_frontend
    command: sh -c "npm run dev"
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    volumes:
      - frontend:/usr/app
    networks:
      - internal


volumes:
  postgres-db:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
