# Generated by Django 5.0.4 on 2024-04-26 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentPlan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], max_length=5, unique=True)),
                ('instance_tier', models.CharField(choices=[('t2', 't2'), ('t3', 't3'), ('t3a', 't3a'), ('t4g', 't4g')], max_length=10)),
                ('instance_type', models.CharField(choices=[('nano', 'Nano'), ('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'xLarge'), ('2xlarge', '2xLarge')], max_length=10)),
            ],
            options={
                'ordering': ('-modified_at',),
            },
        ),
    ]
